name: Web and API Automation workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    #ini untuk download repo
    - uses: actions/checkout@v3

    #ini untuk setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    #ini untuk setup browser
    - name: Set up browser Edge
      uses: browser-actions/setup-edge@v1.1.0

    #ini untuk setup gradlew
    - name: Set up gradlew
      run : chmod +x gradlew

    #ini untuk execute gradle command untuk execute testnya
    - name: Execute API test
      run : ./gradlew apiTest
